# Form implementation generated from reading ui file 'Interface_RU2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(522, 674)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color: rgb(45, 45, 45);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.Int_Numbers_Only = QtWidgets.QLabel(parent=self.centralwidget)
        self.Int_Numbers_Only.setGeometry(QtCore.QRect(20, 10, 261, 50))
        self.Int_Numbers_Only.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(53, 53, 53);\n"
"    border-radius: 10px;\n"
"}")
        self.Int_Numbers_Only.setObjectName("Int_Numbers_Only")
        self.Coins = QtWidgets.QLabel(parent=self.centralwidget)
        self.Coins.setGeometry(QtCore.QRect(20, 70, 111, 50))
        self.Coins.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(53, 53, 53);\n"
"    border-radius: 10px;\n"
"}")
        self.Coins.setObjectName("Coins")
        self.Bombs = QtWidgets.QLabel(parent=self.centralwidget)
        self.Bombs.setGeometry(QtCore.QRect(20, 125, 111, 50))
        self.Bombs.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(53, 53, 53);\n"
"    border-radius: 10px;\n"
"}")
        self.Bombs.setObjectName("Bombs")
        self.Keys = QtWidgets.QLabel(parent=self.centralwidget)
        self.Keys.setGeometry(QtCore.QRect(20, 180, 111, 50))
        self.Keys.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(53, 53, 53);\n"
"    border-radius: 10px;\n"
"}")
        self.Keys.setObjectName("Keys")
        self.Active_items = QtWidgets.QLabel(parent=self.centralwidget)
        self.Active_items.setGeometry(QtCore.QRect(20, 235, 111, 50))
        self.Active_items.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 11pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(53, 53, 53);\n"
"    border-radius: 10px;\n"
"}")
        self.Active_items.setObjectName("Active_items")
        self.Change_coins = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Change_coins.setGeometry(QtCore.QRect(290, 70, 120, 50))
        self.Change_coins.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Change_coins.setObjectName("Change_coins")
        self.Input_coins = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_coins.setGeometry(QtCore.QRect(140, 70, 141, 50))
        self.Input_coins.setStyleSheet("QLineEdit{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid rgb(37, 39, 48, 0);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding-left: 20 px;\n"
"    padding-right: 20 px;\n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(104, 104, 104);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(141, 141, 141);\n"
"}")
        self.Input_coins.setObjectName("Input_coins")
        self.Input_bombs = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_bombs.setGeometry(QtCore.QRect(140, 125, 141, 50))
        self.Input_bombs.setStyleSheet("QLineEdit{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid rgb(37, 39, 48, 0);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding-left: 20 px;\n"
"    padding-right: 20 px;\n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(104, 104, 104);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(141, 141, 141);\n"
"}")
        self.Input_bombs.setObjectName("Input_bombs")
        self.Input_keys = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_keys.setGeometry(QtCore.QRect(140, 180, 141, 50))
        self.Input_keys.setStyleSheet("QLineEdit{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid rgb(37, 39, 48, 0);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding-left: 20 px;\n"
"    padding-right: 20 px;\n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(104, 104, 104);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(141, 141, 141);\n"
"}")
        self.Input_keys.setObjectName("Input_keys")
        self.Input_items = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Input_items.setGeometry(QtCore.QRect(140, 235, 141, 50))
        self.Input_items.setStyleSheet("QLineEdit{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border: 2px solid rgb(37, 39, 48, 0);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding-left: 20 px;\n"
"    padding-right: 20 px;\n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(104, 104, 104);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(141, 141, 141);\n"
"}")
        self.Input_items.setObjectName("Input_items")
        self.Change_bombs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Change_bombs.setGeometry(QtCore.QRect(290, 125, 120, 50))
        self.Change_bombs.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Change_bombs.setObjectName("Change_bombs")
        self.Change_keys = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Change_keys.setGeometry(QtCore.QRect(290, 180, 120, 50))
        self.Change_keys.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Change_keys.setObjectName("Change_keys")
        self.Change_items = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Change_items.setGeometry(QtCore.QRect(290, 235, 120, 50))
        self.Change_items.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Change_items.setObjectName("Change_items")
        self.Infinity_coins = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Infinity_coins.setGeometry(QtCore.QRect(420, 70, 84, 50))
        self.Infinity_coins.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Infinity_coins.setObjectName("Infinity_coins")
        self.Infinity_bombs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Infinity_bombs.setGeometry(QtCore.QRect(420, 125, 84, 50))
        self.Infinity_bombs.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Infinity_bombs.setObjectName("Infinity_bombs")
        self.Infinity_keys = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Infinity_keys.setGeometry(QtCore.QRect(420, 180, 84, 50))
        self.Infinity_keys.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Infinity_keys.setObjectName("Infinity_keys")
        self.D6_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.D6_btn.setGeometry(QtCore.QRect(420, 235, 84, 50))
        self.D6_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.D6_btn.setObjectName("D6_btn")
        self.Inf_energy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Inf_energy.setGeometry(QtCore.QRect(260, 480, 241, 50))
        self.Inf_energy.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Inf_energy.setObjectName("Inf_energy")
        self.Dmg_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Dmg_btn.setGeometry(QtCore.QRect(260, 540, 241, 50))
        self.Dmg_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Dmg_btn.setObjectName("Dmg_btn")
        self.Inf_hearts_coins = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Inf_hearts_coins.setGeometry(QtCore.QRect(260, 420, 241, 50))
        self.Inf_hearts_coins.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Inf_hearts_coins.setObjectName("Inf_hearts_coins")
        self.Inf_red_hearts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Inf_red_hearts.setGeometry(QtCore.QRect(261, 300, 241, 50))
        self.Inf_red_hearts.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Inf_red_hearts.setObjectName("Inf_red_hearts")
        self.Inf_blue_hearts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Inf_blue_hearts.setGeometry(QtCore.QRect(260, 360, 241, 50))
        self.Inf_blue_hearts.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Inf_blue_hearts.setObjectName("Inf_blue_hearts")
        self.Exit_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Exit_btn.setGeometry(QtCore.QRect(20, 610, 120, 50))
        self.Exit_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Exit_btn.setObjectName("Exit_btn")
        self.Inform_board = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Inform_board.setGeometry(QtCore.QRect(20, 310, 191, 271))
        self.Inform_board.setStyleSheet("QTextBrowser{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    background-color: rgb(45, 45, 45);\n"
"}\n"
"")
        self.Inform_board.setObjectName("Inform_board")
        self.Language_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Language_btn.setGeometry(QtCore.QRect(420, 10, 84, 50))
        self.Language_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Language_btn.setObjectName("Language_btn")
        self.Hook_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Hook_btn.setGeometry(QtCore.QRect(290, 10, 120, 50))
        self.Hook_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 6px;\n"
"    background-color: rgb(69, 69, 69);\n"
"    min-width: 80px;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(50, 50, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(64, 64, 64);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; \n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; \n"
"}")
        self.Hook_btn.setObjectName("Hook_btn")
        self.Author_btn = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.Author_btn.setGeometry(QtCore.QRect(260, 630, 191, 31))
        self.Author_btn.setStyleSheet("QTextBrowser{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(136, 106, 22, 255), stop:0.119403 rgba(166, 140, 41, 255), stop:0.233831 rgba(204, 181, 74, 255), stop:0.293532 rgba(235, 219, 102, 255), stop:0.383085 rgba(245, 236, 112, 255), stop:0.502488 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.61194 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.80597 rgba(208, 187, 73, 255), stop:0.835821 rgba(187, 156, 51, 255), stop:0.890547 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));\n"
"}")
        self.Author_btn.setObjectName("Author_btn")
        self.Icon_author = QtWidgets.QLabel(parent=self.centralwidget)
        self.Icon_author.setGeometry(QtCore.QRect(460, 620, 41, 41))
        self.Icon_author.setStyleSheet("QLabel{\n"
"    background-image: url(:/newPrefix/imgonline-com-ua-Resize-FJDPqgFmfYQzOIw.jpg);\n"
"}")
        self.Icon_author.setText("")
        self.Icon_author.setObjectName("Icon_author")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Isaac`s Cheats"))
        self.Int_Numbers_Only.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Только целые числа!</p></body></html>"))
        self.Coins.setText(_translate("MainWindow", "Монеты"))
        self.Bombs.setText(_translate("MainWindow", "Бомбы"))
        self.Keys.setText(_translate("MainWindow", "Ключи"))
        self.Active_items.setText(_translate("MainWindow", "ID Активки"))
        self.Change_coins.setText(_translate("MainWindow", "Изменить"))
        self.Change_bombs.setText(_translate("MainWindow", "Изменить"))
        self.Change_keys.setText(_translate("MainWindow", "Изменить"))
        self.Change_items.setText(_translate("MainWindow", "Изменить"))
        self.Infinity_coins.setText(_translate("MainWindow", "∞ 99"))
        self.Infinity_bombs.setText(_translate("MainWindow", "∞ 99"))
        self.Infinity_keys.setText(_translate("MainWindow", "∞ 99"))
        self.D6_btn.setText(_translate("MainWindow", "D6"))
        self.Inf_energy.setText(_translate("MainWindow", "Бесконечные заряды"))
        self.Dmg_btn.setText(_translate("MainWindow", "100 урона"))
        self.Inf_hearts_coins.setText(_translate("MainWindow", "Бесконечные сердца-монеты"))
        self.Inf_red_hearts.setText(_translate("MainWindow", "Бесконечные красные сердца"))
        self.Inf_blue_hearts.setText(_translate("MainWindow", "Бесконечные синие сердца"))
        self.Exit_btn.setText(_translate("MainWindow", "Выход"))
        self.Inform_board.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 1</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Hook</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 2</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Бесконечные красные сердца</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 3</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Бесконечные синие сердца</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 4</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Бесконечные сердца-монеты</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 5</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Бесконечные монеты</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 6</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Бесконечные бомбы</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 7</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Бесконечные ключи</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 8</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - Бесконечная энергия</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\"> Left Ctrl + 9</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"> - 100 урона</span></p></body></html>"))
        self.Language_btn.setText(_translate("MainWindow", "RU/EN"))
        self.Hook_btn.setText(_translate("MainWindow", "Hook"))
        self.Author_btn.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">   Made by GAVKOSHMIG Inc.</span></p></body></html>"))
