# Form implementation generated from reading ui file 'ui_imagedialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageDIalog(object):
    def setupUi(self, ImageDIalog):
        ImageDIalog.setObjectName("ImageDIalog")
        ImageDIalog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ImageDIalog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(ImageDIalog)
        self.buttonBox.accepted.connect(ImageDIalog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImageDIalog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageDIalog)

    def retranslateUi(self, ImageDIalog):
        _translate = QtCore.QCoreApplication.translate
        ImageDIalog.setWindowTitle(_translate("ImageDIalog", "Dialog"))
